Todo/Models/ErrorViewModel.cs
namespace Todo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Todo/Models/ToDoItem.cs
using System.ComponentModel.DataAnnotations;

namespace Todo.Models
{
    public class ToDoItem
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }=string.Empty;

        [Required]
        public string Description { get; set; }=String.Empty;


        public bool IsCompleted { get; set; }

        [Required]

        public DateOnly DueDate { get; set; }
    }
}

Todo/ViewModels/CreateToDoItemViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Todo.ViewModels
{
    public class CreateToDoItemViewModel
    {

      

        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; } = string.Empty;

        [Required]
        [Display(Name = "Description")]
        public string Description { get; set; } = String.Empty;


        public bool IsCompleted { get; set; }

        [Required]
        [Display(Name = "DueDate")]

        public DateOnly DueDate { get; set; }


    }
}

Todo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Todo.Models;

namespace Todo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Todo/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Mvc;
using Todo.Data;
using Todo.Interfaces;
using Todo.Models;
using Todo.ViewModels;

namespace Todo.Controllers
{
    public class ToDoController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly IToDoRepository _todoRepo;
        public ToDoController(ApplicationDbContext dbContext, IToDoRepository TodoRepo)
        {
            _context = dbContext;
            _todoRepo = TodoRepo;
        }
        public IActionResult Index()
        {
            var todoitems=_context.ToDoItems.ToList();

            return View(todoitems);
        }


        public IActionResult CreateToDo()
        {


            return View();
        }

        [HttpPost]
        public IActionResult CreateToDo(CreateToDoItemViewModel createToDoItemViewModel)
        {

           ToDoItem toDoItem = new ToDoItem
           {
               Title= createToDoItemViewModel.Title,
               Description= createToDoItemViewModel.Description,
               IsCompleted= createToDoItemViewModel.IsCompleted,
               DueDate= createToDoItemViewModel.DueDate,

           };
            _context.Add(toDoItem);


            return View("Index");
        }
    }
}

Todo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Todo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Todo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Todo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Todo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="CreateToDO">CreateToDO</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Todo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Todo/Views/ToDo/CreateToDo.cshtml
@using Todo.ViewModels

@model CreateToDoItemViewModel




<form asp-action="CreateToDo" asp-controller="ToDo" method="post" role="form">

    <h4>Create ToDoItem</h4>
    <hr />

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Title" class="col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Description" class="col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="IsCompleted"></label>
        <input asp-for="IsCompleted" type="checkbox" class="form-check-input" />
    </div>

    <div class="form-group">
        <label asp-for="DueDate"></label>
        <input asp-for="DueDate" type="date" class="form-check-input" />
    </div>

    <div class="form-group">
        <div class="offset-md-2 col-md-10">
            <button type="submit" class="btn btn-success">Register</button>
        </div>
    </div>

</form>

Todo/Views/ToDo/Index.cshtml
@model IEnumerable<ToDoItem>



@{

    foreach(var item in Model)
    {
        <h1>@item.Title</h1>
    }

}